- datajoint/base.py
- doc/Makefile
- doc/source/Getting started.rst
- doc/source/base.rst
- doc/source/connection.rst
- doc/source/index.rst
- doc/source/relational.rst
- tutorials/Getting started.ipynb
* While commenting, I had a few questions/issues. Please check the todos in the code
* I changed the definition of base.Base.add_attribute. I dropped the kwarg first in favour of after=None. By default after=None inserts first, if after is not None, then it inserts after the given attribute.
* I added a directory called tutorials. It can contain ipython notebooks tutorials. When calling "make tutorials" within the directory doc, the notebooks are converted to rst and copied into the source folder of doc.
> Commented base module and added tutorial

- datajoint/settings.py
- tests/test_settings.py
* responding to Edgar's comment, Config now raises a ValueError if you attempt to set nested settings.
> test for nested settings

- datajoint/autopopulate.py
- datajoint/free_relation.py
- datajoint/relational_operand.py
- tests/test_relation.py
- tests/test_relational_operand.py
closing issue #4.  Still need to create unit tests.
> basic autopopulate works.

- datajoint/autopopulate.py
Change the name of `pop_rel` to `populate_relation` per discussion that took place in #59
> Change pop_rel to populate_relation

- datajoint/dependencies.py
- `populated_from` did not work because the dependencies were not loaded
-  as a result `progress` did not work either
- fixed it the way @eywalker recommended
> fix missing dependencies bug

- datajoint/connection.py
- setup.py
* since version 0.7.2 which I put in the `setup.py` requirements
* dropped the hack for large packet's in `connection.py`
> pymysql works with larger blobs

- datajoint/base_relation.py
causes SELECT * to be used rather tha SELECT attr1, ..., attrN when possible.
> minor fix for previous commit

- datajoint/relational_operand.py
- mouse over tooltip with attribute comment
- all the other stuff is just PEP8 formatting
> tooltip for jupyter output

- .travis.yml
- datajoint/base_relation.py
- datajoint/fetch.py
- datajoint/relational_operand.py
- datajoint/schema.py
- datajoint/settings.py
- tests/__init__.py
- tests/schema.py
- tests/test_blob2.py
- tests/test_cascading_delete.py
- tests/test_connection.py
- tests/test_fetch.py
- tests/test_fetch_deprecated.py
- tests/test_privileges.py
- tests/test_relational_operand.py
- tests/test_schema.py
- tests/test_settings.py
Fixed
* #334 -- handling of the Decimal datatype in restrictions
* #241 -- handling of insufficient privileges.  This was already fixed.  I just added tests.
> Fixed #334 and #241

- datajoint/relational_operand.py
There was a bug introduced in #394.  The column names were reordered by the body of the displayed table was not.  E.g.
In this example, the blob should be in `flip_times`. 
This fixes it.
> Fix a bug introduced in #394 -- incorrect column order in HTML preview

- datajoint/connection.py
> Suppress MySQL mode related warnings

- datajoint/__init__.py
- datajoint/autopopulate.py
- datajoint/base_relation.py
- datajoint/connection.py
- datajoint/declare.py
- datajoint/user_relations.py
- tests/schema.py
- tests/schema_advanced.py
- tests/test_relation.py
Work in progress, provided for preliminary review. Do not merge.
* Fix #301 -- WIP, still need to fix `describe` and `delete`
* Fix #491
> Partial implementation of nullable foreign key

- datajoint/__init__.py
- datajoint/admin.py
- datajoint/settings.py
- datajoint/utils.py
In #509, `admin.set_password` attempted to use `dj.config` without importing `dj.config`.
> fix bug introduced in last PR #509

- docs-parts/definition/01-Creating-Schemas_lang1.rst
- docs-parts/index_lang1.rst
Fixes datajoint/datajoint-docs#96.
> Add Python-specific index.rst and note import as dj 

- Dockerfile
- datajoint/connection.py
- datajoint/declare.py
- tests/test_declare.py
- tests/test_privileges.py
Enhancement fix for issue #596. Added integer as a synonym for int.
> Enhancement fix for issue #596. Added integer as a synonym for int.

- datajoint/fetch.py
- tests/test_fetch_same.py
Will convert array from python object to appropriate data type if all elements are of the same type.
> Fix issue #587.

- .travis.yml
- datajoint/blob.py
- tests/__init__.py
- tests/test_blob.py
Add blob packing support for np.bool_ and numpy array of string + integrate creation of test users into unit tests.
> Update blob packing + incorporate test user creation into nose

- requirements.txt
> Add matplotlib as pip requirement

- datajoint/declare.py
> fix pyparsing.Or bug introduced by pyparsing 2.4.1

- datajoint/declare.py
Merge fixes from #631 into dev too
> Merge pyparsing fix from master 

- datajoint/fetch.py
- tests/schema.py
- tests/test_fetch.py
- tests/test_fetch_same.py
Fixes an issue introduced in `0.12.dev5` pre-release
* Fixes #647
> Fix fetches of nullable integer attributes

- .dockerignore
- Dockerfile
> Fix lingering docker build permission issues

- datajoint/admin.py
- docs-parts/computation/06-distributed-computing_kill_order_by.rst
> datajoint/admin.py: add order_by argument to dj.kill (#668)

- .gitignore
- LNX-docker-compose.yml
- datajoint/admin.py
- datajoint/connection.py
- datajoint/dependencies.py
- datajoint/external.py
- datajoint/migrate.py
- local-docker-compose.yml
> Fix MySQL8 case-sensitivity issue

- .gitignore
- CHANGELOG.md
- LNX-docker-compose.yml
- README.md
- datajoint/admin.py
- datajoint/attribute_adapter.py
- datajoint/connection.py
- datajoint/dependencies.py
- datajoint/external.py
- datajoint/heading.py
- datajoint/migrate.py
- datajoint/schemas.py
- datajoint/version.py
- docs-parts/intro/Releases_lang1.rst
- local-docker-compose.yml
- setup.py
- tests/__init__.py
- tests/test_fetch_same.py
- tests/test_jobs.py
- tests/test_reconnection.py
- tests/test_schema.py
Pull in new updates to `master` to prepare for special release `0.12.7b1`.
> Master -> Plugin

- .gitignore
- CHANGELOG.md
- LNX-docker-compose.yml
- README.md
- datajoint/admin.py
- datajoint/attribute_adapter.py
- datajoint/connection.py
- datajoint/dependencies.py
- datajoint/external.py
- datajoint/heading.py
- datajoint/migrate.py
- datajoint/schemas.py
- datajoint/version.py
- docs-parts/intro/Releases_lang1.rst
- local-docker-compose.yml
- setup.py
- tests/__init__.py
- tests/test_fetch_same.py
- tests/test_jobs.py
- tests/test_reconnection.py
- tests/test_schema.py
Note: `pre` is our stable branch where users may safely pull from. It should match with the latest release (or pre-release) in [PyPi](https://pypi.org/project/datajoint/).
> Master -> Pre

- datajoint/connection.py
- datajoint/diagram.py
- datajoint/expression.py
- datajoint/fetch.py
- datajoint/schemas.py
Adding query caching to the pre-release.
> Query cache

- datajoint/blob.py
- datajoint/fetch.py
- datajoint/version.py
> Cascade delete

- docs-parts/queries/03-Fetch_lang1.rst
> 03-Fetch_lang1.rst: explain DataFrame index as matching pkey

- CHANGELOG.md
- datajoint/connection.py
- docs-parts/intro/Releases_lang1.rst
- tests/test_connection.py
> Fix issue with explicit calls to `dj.Connection`

- CHANGELOG.md
- datajoint/external.py
- datajoint/table.py
- docs-parts/intro/Releases_lang1.rst
- tests/test_foreign_keys.py
> fix the counting of deleted items. Issue #897

- LNX-docker-compose.yml
- README.md
- local-docker-compose.yml
- tests/test_s3.py
> Update test_s3 to work for undockerized testing

- docs-parts/computation/01-autopopulate_lang1.rst
- docs-parts/definition/11-ERD_lang1.rst
- docs-parts/definition/11-ERD_lang2.rst
- docs-parts/definition/11-ERD_lang3.rst
- docs-parts/definition/11-ERD_lang4.rst
- `ERD` to `Diagram`
- `insert` to `insert1`
> Fix documentation

- .gitignore
- datajoint/settings.py
--- Logging error --- 
`TypeError: not all arguments converted during string formatting`
> fix(logging): :bug: fix arguments sent to logger during config update

- tests/test_filepath.py
- cp to tests
- Migrate test_filepath.py
> PLAT-158: Migrate test_filepath.py

- tests/test_fetch_same.py
- Changes from #1129
- cp to tests
- Migrate test_fetch_same
> PLAT-157: Migrate test_fetch_same

- tests/test_uuid.py
- cp to tests
- nose2pytest test_uuid
- Migrate test_uuid
> PLAT-170: Migrate test_uuid

- docs/mkdocs.yaml
Fix documentation builds that are failing, such as https://github.com/datajoint/datajoint-python/actions/runs/10514098880/job/29131407848
> Fix CD docs build

- .github/workflows/development.yaml
Fixes error encountered in 0.14.3 release: https://github.com/datajoint/datajoint-python/actions/runs/10996995479/job/30531905701
> Fix CI for 0.14.3 release

- .github/workflows/development.yaml
Update development.yaml to include testing for Python 3.13
> Test Python 3.13 in CI

- README.md
- datajoint/version.py
Manually creating the PR for the failed auto PR job.
> Update version 0.14.5
