datajoint/datajoint-python

datajoint/base.py, tests/test_base.py
* base.Base.declaration has been replaced with base.Base._table_def
* made base.py PEP8 compliant using autopep8
=> Merged base.Base.declaration with base.Base._table_def

.gitignore, datajoint/__init__.py, datajoint/base.py, datajoint/blob.py, datajoint/connection.py, datajoint/erd.py, datajoint/heading.py, datajoint/relational.py, datajoint/settings.py, datajoint/utils.py, setup.py, tests/test_base.py, tests/test_connection.py, tests/test_core.py, tests/test_settings.py
* moved DataJointError to __init__
* moved logger to settings
* renamed core into utils
* implemented settings.Config
* instantiate datajoint.config in __init__
* wrote tests for settings
=> Settings reimplemented

datajoint/base.py, datajoint/declare.py, datajoint/heading.py, datajoint/relational.py, datajoint/table.py, tests/schemata/schema1/test1.py, tests/schemata/schema1/test2.py, tests/schemata/schema1/test3.py
Went through and fixed many of the broken links in the datajoint introduced by #39. Now some tests passes. However there still remains an issue about how table declaration is handled. Refer to issue #40 for a detailed explanation.
=> Fix references and name changes

datajoint/base.py, datajoint/settings.py, datajoint/table.py, tests/__init__.py, tests/test_table.py
* insert now takes single tuples, lists, records, or dictionaries
* added additional functions batch_insert and iter_insert
* added a bunch of tests for insert
=> fixed insert of table, and added batch_insert and iter_insert

datajoint/base.py, datajoint/connection.py, datajoint/table.py, tests/__init__.py, tests/schemata/schema1/__init__.py, tests/schemata/schema1/test1.py, tests/schemata/schema1/test2.py, tests/schemata/schema1/test3.py, tests/schemata/schema2/__init__.py, tests/schemata/schema2/test1.py, tests/test_base.py, tests/test_connection.py, tests/test_utils.py
I have rearranged methods in Table and Base such that most of the declaration related logic is now found in the Table class. Ability to resolve module names are provided by Base through the use of overridden method `get_base`.
I have also added quite a few test cases covering various scenarios of using Base derivatives including referencing across schema, and referencing a schema bound to a package.
=> Rearrange logic in Table and Base

datajoint/Relation.py, datajoint/__init__.py, datajoint/autopopulate.py, datajoint/free_relation.py, datajoint/relational_operand.py, demos/demo1.py, doc/source/Getting started.rst, doc/source/base.rst, tests/schemata/schema1/test1.py, tests/schemata/schema1/test2.py, tests/schemata/schema1/test3.py, tests/schemata/schema1/test4.py, tests/schemata/schema2/test1.py, tests/test_base.py, tests/test_table.py
Three classes and its respective module names have been refactors as following:
* `Relation` -> `RelationalOperand`
* `relation.py` -> `relational_operand.py`
* `Table` -> `FreeRelation`
* `table.py` -> `free_relation.py`
* `Base` -> `Relation`
* `base.py` -> `relation.py`
These are major name changes, so please make sure to base any future work off of this.
=> Refactored Relation, Table and Base

datajoint/free_relation.py, datajoint/heading.py, datajoint/relational_operand.py, datajoint/utils.py, tests/test_relation.py
* `RelationalOperand.__iter__` doesn't take any arguments anymore
* `RelationalOperand.__iter__` yields dicts
* fetch returns a record array or a list of dicts if requested
* positional insert not supported anymore
* added check for existing attribute names in `FreeRelation.insert`
* Insert now accepts everything that is an instance of `collections.Mapping`. This is the minimum requirement we need and gives a lot of flexibility to the user.
=> cleaned up __iter__  and fetch logic

datajoint/free_relation.py, datajoint/relational_operand.py, demos/demo1.py, tests/schemata/schema1/test1.py, tests/schemata/schema1/test2.py, tests/schemata/schema2/test1.py, tests/test_blob.py, tests/test_relation.py
This bug was detected by Fabian and included in the nose test.  The test passes now.
=> Fixed bug in the semijoin operator

datajoint/free_relation.py, datajoint/relational_operand.py, demos/rundemo1.py, tests/test_relation.py
In many cases, especially from within `_make_tuples`, queries must return exactly one tuple.  This is communicated by calling `fetch1` in place of `fetch`.   The return result is a single dict.  An error is thrown if the number of tuples is not 1.
=> added RetlationalOperand.fetch1()

datajoint/free_relation.py, datajoint/relation.py, requirements.txt, tests/schemata/schema1/test1.py, tests/test_free_relation.py, tests/test_relation.py
* Allow for reference to a table in same module or database to omit the module name/database name
* Add a test case for the shorthand notation
=> Add foreign reference shorthand. close #73

datajoint/settings.py, tests/__init__.py, tests/schemata/schema1/test1.py
* the default for safemode in settings is now True
* safemode is set to false in `__init__` of tests
* changes in config are logged on level INFO via `__getitem__`
=> safemode=True by default and configchange logging

datajoint/autopopulate.py, datajoint/connection.py, datajoint/erd.py, datajoint/free_relation.py, demos/demo1.py, tests/test_connection.py
Basic implementation of ERD is done with few other changes including
* fixed bug pertaining to non-primary key foreign reference
* fixed bug in `connection` object's mapping of parent and reference relations, introduced previously due to change in regular expression
=> ERD implementation

datajoint/__init__.py, datajoint/autopopulate.py, datajoint/connection.py, datajoint/decorators.py, datajoint/free_relation.py, requirements.txt, setup.py, tests/schemata/schema1/test1.py, tests/test_connection.py, tests/test_relation.py
* created a decorator `@not_in_transaction` that throws a TransactionError if the decorated function is called during a transaction
* If an error is thrown, the Transaction object rolls back the current transaction and hands the error to the next level
* `populate` explicitly catches the TransactionError. The TransactionError object holds the function and the parameters that caused the error. It uses that to provide a function `resolve` which just calls the function again with the same arguments. So if `populate` catches a TransactionError, it can just call `resolve` (because it is not in a transaction anymore), resolve the error, and restart the transaction.
=> Avoid implicit commits

datajoint/relation.py
I have made a few changes on how `Relation` object instantiation is handled. Following is a summary:
* There now exists `Relation` and its subclass `ClassRelation`
* `Relation` can be instantiated directly, taking in name of table, name of schema, `connection` object, table definition, and `context` dictionary. This allows for one to manipulate tables quickly without having to write a dedicated class
* Each direct instance of `Relation` may (and will likely) point to different tables on potentially different schema or even different database servers - there is no class level binding
* `ClassRelation` is a subclass of `Relation` that is designed from ground up to be bound to a specific schema & database at the class level - this way every instance of `ClassRelation` derivative is already …
=> Add ClassRelation

datajoint/blob.py, datajoint/connection.py, datajoint/declare.py, datajoint/erd.py, datajoint/relation.py
The ERD class loads dependencies.  It has a narrow interface.  An instance of ERD is created in the Connection object and dependencies are loaded by the schema decorator at the time of class declaration.
=> Implemented loading of dependencies.

datajoint/relation.py, datajoint/relational_operand.py, tests/schema.py
* Implemented cascading delete with proper restriction handling, addressing #15
* Fix bug pertaining to projection operation on relation already restricted by another relation. For details, please refer to #129
* Added seed to random number generation in tests, addressing #128
* Expanded the implementation of `_restrict` in `RelationalOperand` to accept a list of restrictions. This done for implementing cascading delete. However, it's very likely that a cleaner solution exists.
It passes all existing tests after the modification, and I have run a number of checks locally, but haven't got to write tests covering new operations.
=> Cascading Delete Implementation

datajoint/autopopulate.py, datajoint/connection.py, datajoint/fetch.py, datajoint/relational_operand.py, tests/test_relational_operand.py
- the behavior of `relation.fetch()` and `relation.fetch1()` should be reproduced
- `relation.keys()` moved to `relation.fetch.keys()`
- `relation.values()` was removed and is now `relation.fetch.__iter__()`
It probably needs more thorough testing, but I put it up so we can start using it.
=> Fetch object

datajoint/fetch.py, datajoint/relational_operand.py, tests/schema.py, tests/test_fetch.py, tests/test_relational_operand.py
- `relation.fetch.order_by` allows for individual sorting arguments now. I removed the kwarg `descending`. The new syntax is `relation.fetch.order_by('name DESC', 'trial', 'stimulus DESC')`. If the sorting argument is omitted, ASC is set by default. 
- I removed the `relation.fetch.apply` function. It is not needed at the moment and simplified the syntax substantially. Additionally, it might cause confusion, since something like `relation.fetch.apply(myfunc).order_by('stimulus')['name']` suggests that the function is applied in the beginning, but it would have been applied at the end. 
- I renamed `FetchQuery` to `Fetch` and `Fetch1Query` to `Fetch1`
- I renamed `limit_by` to `limit_to`. Dimitri actually prefers `limit`, but I think `limit_to` is more consistent with `order_by`. 
- Wrote …
=> Extended order_by and bugfixes

datajoint/fetch.py, datajoint/relation.py, datajoint/schema.py, datajoint/user_relations.py, tests/schema.py, tests/test_fetch.py
- Test fetch table normal form
- `prepare` renamed to `_prepare`
- `order_by` overwrites **all** previous ordering settings
=> Work on fetch objects and rename `_prepare`

datajoint/fetch.py, tests/test_fetch.py
- `limit_to` is now `limit`
- `offset_by` is now `offset`
- `offset` without `limit` sets limit to `2*len(fetch._relation)` at fetch time.
=> Limit and offset in fetch object

datajoint/fetch.py, datajoint/relation.py, datajoint/relational_operand.py, tests/test_fetch.py
* Moved table preview into `Fetch` object's `__repr__`
* Modify 'RelationalOperand`'s `__repr__` to represent the constituent relational operation 
* Add `__len__` onto `Fetch` object
`Fetch1` object's `__repr__` was not touched as it didn't quite make sense for this to be previewable (should only be one row, and fetching it for display costs about the same as just grabbing it).
=> Rearrange `__repr__`

datajoint/__init__.py, datajoint/schema.py, datajoint/user_relations.py, tests/schema.py, tests/schema_simple.py, tests/test_autopopulate.py, tests/test_cascading_delete.py, tests/test_declare.py, tests/test_relation.py, tests/test_relational_operand.py
Subordinate relations are now declared as nested classes.  
See `tests/schema.py` and `tests/schema_simple.py` for examples.
(Corrected: typo)
=> Solved #146.

datajoint/__init__.py, datajoint/autopopulate.py, datajoint/kill.py, datajoint/relation.py, datajoint/schema.py, datajoint/user_relations.py
- Minor cleanup
- Added the `order` parameter to AutoPopulate.populate()
- For Part relations, prepare is now called after their tables are declared.
=> Added the option to randomize AutoPopulate order.  Improved the timing of prepare calls for Part relations.

datajoint/relation.py, datajoint/relational_operand.py, tests/test_jobs.py
Converging dependencies are now handled correctly in deletes.
Also, `rel & [cond1, cond2, ...]` now works for any type of conditions, including relations and strings. The conditioned are ORed in this case.
=> Fixed issue #15

datajoint/relational_operand.py
ipython notebook uses `_repr_html_` to output objects. For example
```
from schema import myRelation
myRelation()
```
will now output a nice html version of the relation. Just as in pandas.
=> add _repr_html_ for ipython notebook output

datajoint/__init__.py, datajoint/base_relation.py, datajoint/schema.py, tests/test_declare.py
So far, if a schema is defined in matlab, the corresponding class in python does not define a definition (for consistency). The syntax is 
```python
class MyMatlabTable(dj.Tier):
definition = None
```
```python
class MyMatlabTable(dj.Tier):
definition = ...
```
The problem is that this will raise an error if the matlab table has not yet been defined in the database. This pull request solves that by checking whether `definition=None` or `definition=...` in `BaseRelation.declare`. If that is the case, then the table is not declared and a warning is raised. 
I refrained from overriding the constructor because the user might have defined a constructor and I didn't want to mess with that.
=> tables are not declare if definition is None or Ellipsis

.coveragerc, .coveralls.yml, .travis.yml, datajoint/base_relation.py, datajoint/fetch.py, datajoint/relational_operand.py, datajoint/settings.py, tests/schema.py, tests/schema_simple.py, tests/test_relational_operand.py
* `__repr__` from fetch object moved back to `relational_operand`. `__repr__` prints out a short version if loglevel is DEBUG
* fetch object got its own `__repr__`
=> fix issue #186

datajoint/autopopulate.py, datajoint/base_relation.py, datajoint/user_relations.py
=> handled the case when insert received a collection of rows with differently ordered fields.

.gitignore, .travis.yml, datajoint/base_relation.py, tests/test_cascading_delete.py
In `base_relation.py` `delete` method, we modify the content of the OrderedDict `relations` while traversing using its `values()` iterator, thus modifying the iterator! https://github.com/datajoint/datajoint-python/blob/master/datajoint/base_relation.py#L360-L367
It turns out that modification of the OrderedDict iterator is OK in Python 3.4 (although still not recommended) but simply fails in Python 3.5. The code has been fixed such that we are no longer using direct iterator if the OrderedDict is to be modified in the loop.
I also added Python 3.5 to the test target platform for Travis CI, addressing #198
=> Mutation of OrderedDict iterator during the loop

Dockerfile, JupyterDockerfile, docker-compose.yml
* Updated `Dockerfile` to creating DataJoint container by using locally available code rather than the indirect reference to GitHub content
* Added `docker-compose.yml` so that you can run `docker-compose up` to launch a Jupyter notebook server along with a MySQL server to have a complete working environment for DataJoint. Will be ideal for just testing/playing with DataJoint.
=> Docker related enhancements

datajoint/__init__.py, datajoint/autopopulate.py, datajoint/fetch.py, datajoint/heading.py, datajoint/relational_operand.py, datajoint/schema.py, datajoint/settings.py, datajoint/user_relations.py, tests/test_autopopulate.py, tests/test_relational_operand.py
Restrictions by AndLists and OrLists now work correctly
- `rel & []`  is equivalent to `rel & dj.OrList()`
- `rel & []` produces  the empty relation
- `rel - []` has no effect
- `rel & dj.AndList((cond1, cond2))` is equivalent to `rel & cond1 & cond2`
- `rel & dj.AndList()` has no effect
- `rel - dj.AndList()` produces the empty relation
Also, `rel.restriction` is now of type `dj.AndList`.
Also, `RelationalOperand.project` has been renamed to  `RelationalOperand.proj`  (issue #202) with `project` aliased to `proj` for backward compatibility.
=> Fixed restrictions by empty AndLists and OrLists.

.travis.yml, requirements.txt
Introduction of `scipy` as part of requirements required a number of changes to Travis configuration, including:
* explicit installation of dependencies: BLAS, LAPACK, ATLAS, and Fortran
* extension of Travis time delay to cope with long build time for `scipy`. Travis times out after 10 min of non-response and this was preventing successful build under Python 3.5. Extended this to 30 min.
These modifications allow for `scipy` to be built and the rest of the test to be run. However, building of `scipy` alone extends the test time by nearly 10min, and we might want to look into other methods to speed up the test run time.
=> Configure Travis to work with `scipy` installation

Dockerfile
Update `Dockerfile` to base the `datajoint` image off of the `datajoint/pydev` instead of the original `eywalker/pydev`. This reflects planned changes and deviations of `eywalker/pydev` content from it's current version. Namely, `eywalker/pydev` will be switched to build up on Ubuntu image rather than the current standard `python:3.5` which is ultimately based on a Debian image. `datajoint/pydev` has been created to be a drop-in replacement of the current `eywalker/pydev` and will continue to be based on `python:3.5` image to maintain compatibility.
=> Update Dockerfile to use datajoint/pydev

datajoint/__init__.py, datajoint/autopopulate.py, datajoint/heading.py, datajoint/jobs.py, datajoint/kill.py, datajoint/relational_operand.py, datajoint/schema.py, tests/test_relation_u.py, tests/test_relational_operand.py
- `dj.U` is no longer a `RelationalOperand` -- it only supports a limited number of operations, which produce relational operands. 
- `GroupBy` now uses a `HAVING` clause for restrictions, avoiding an extra subquery. 
- Added `__repr__` to `Schema`. 
- Closing issues #163, #136, #214, #177, #112 -- these should all be fixed.
=> Optimized relational operators

datajoint/__init__.py, datajoint/admin.py, datajoint/base_relation.py, datajoint/connection.py, datajoint/declare.py, datajoint/heading.py, datajoint/schema.py, tests/test_declare.py
The property `real_definition` contains the reversed engineered table definition.  This is useful for updating the definition when changes are made elsewhere.
=> Added `set_password` and `show_definition`

CHANGELOG.md, datajoint/__init__.py, datajoint/base_relation.py, datajoint/connection.py, datajoint/erd.py, tests/test_erd.py
(Copied from CHANGELOG)
* Suppressed warnings (redirected them to logging).  Previoiusly, scipy would throw warnings in ERD, for example.
* Added ERD.from_sequence as a shortcut to combining the ERDs of multiple sources
* ERD() no longer text the context argument.
* ERD.draw() now takes an optional context argument.  By default uses the caller's locals.
=> Improved ERD

CHANGELOG.md, datajoint/__init__.py, datajoint/erd.py, tests/test_erd.py
(Copied from CHANGELOG)
* Added method the `ERD.add_parts` method, which adds the part tables of all tables currently in the ERD.
* `ERD() + arg` and `ERD() - arg` can now accept relation classes as arg.
* `set_password()` now asks for user confirmation.
=> ERD.add_parts

DevDockerfile, datajoint/blob.py, docker-compose.yml, tests/test_blob.py
A dictionary with valid serializable field values (e.g. `np.ndarray` and scalars) can now be serialized and inserted into BLOB. This helps partly address issue #244 and in particular will allow us to solve the issue #243. 
When fetching back BLOB of structure array and if the structure array is a singleton, you can do the following to unpack as dict:
```python
dj.blob.unpack(blob, as_dict=True)
```
This is used to facilitate the testing procedure.
=> Add BLOB support for dict of simple types

datajoint/blob.py, datajoint/fetch.py, tests/test_fetch.py
When fetching data from BLOB, you can now `squeeze` the returned BLOB. Squeezing achieves the following:
* remove singleton dimensions
* convert `numpy` array with only sigleton dimensions into a scalar
* convert flat character `numpy` array into a simple string
Squeezing allows for data structure that is unnecessary bloated (e.g. because of insert from Matlab which always give rise to string as character arrays and arrays of dimensions at least 2).
=> Support `squeeze` of data in BLOB

datajoint/__init__.py, datajoint/base_relation.py, datajoint/relational_operand.py
Failure to create ~log due to MySQL's rules of default values for timestamps.
Added =CURRENT_TIMESTAMP as the default for ~log's primary key.
=> Fixed issue $#259. 

datajoint/__init__.py, datajoint/jobs.py, tests/test_jobs.py
Job table now defaults to accepting longer error message, and when error message is longer than max allowed length, it appropriately truncates the error message with `...truncated` appended to the end. Fix issue #265
=> Fix handling of long error messages in job table

datajoint/__init__.py, datajoint/autopopulate.py
Unlike in Matlab, `populate` does not report how many keys still have to be populated at the beginning of the `populate` invocation. This information is a useful quick indicator.
=> Report how many keys need to be populated

datajoint/__init__.py, datajoint/autopopulate.py, datajoint/settings.py, tests/schema.py, tests/test_jobs.py
* Fixed #276 : `SIGINT` (i.e. `KeyboardInterrupt`) during `populate` is now properly handled just like any standard exceptions during `populate`.
* Fixed #275 : If `SIGINT` (i.e. `CTRL-C`) or `SIGTERM` (closing terminal) signals are received during `populate` with `reserve_jobs=True`, the appropriate job entry status is updated to `error` to indicate that the `populate` process has been terminated
* Error messages entered into the job table now includes the name of the error. Previously exceptions without explicit error message (e.g. `KeyboardInterrupt`) did not produce any `error_message` entry in the job table.
* Added tests for handling of `SIGINT` and `SIGTERM` during the `populate(reserve_jobs=True)` call.
=> Proper handling of SIGINT and SIGTERM during populate

setup.py
Some of the fields for `setup.py` had to be removed to conform to new PyPI standards.
=> Quick fix to the setup.py

datajoint/jobs.py, tests/test_jobs.py
`JobTable` was not properly utilizing the copy constructor of `RelationalOperand`, resulting in erroneous behavior as described in #290. Fixed the handling in `__init__` and added a test case. 
Fixes #290
=> Fix Jobs table to handle multiple restrictions correctly

datajoint/base_relation.py
Otherwise, empty string values, such as those read from empty cells in a spreadsheet, have to be converted manually ahead of time to None or np.nan, which is a real pain.
=> Treat empty string value in numeric field as a nan

datajoint/relational_operand.py
This allows the user to display more or less data, as desired, without having to change the defaults in the `dj_local_conf.json` file.
=> Add limit and width kwargs to preview()

datajoint/__init__.py, datajoint/utils.py
This allows the user to create modules with datajoint classes on the fly. This is particularly useful if one python package wants to use data from another one without the need to install all the dependencies.
=> add `create_virtual_module`

datajoint/schema.py, tests/test_schema_keywords.py
Address issue #302 and #303 
* `Part` tables can now use keyword `master` to refer to the `Master` table, and thus need not know the explicit name of the `Master` table
* You can now easily add new `Part` tables by inheriting from a mix-in class that defines the `Part` table thanks to the indirection of the `Master` table name
* to support this, `schema` decorator looks for all available members for the class (including the inherited ones) to search for `Part` table
* support keyword `self` to refer to the table class that is being decorated. This allows for the definition to use the class attributes pointing to another table (refer to issue #303 for more details)
* added `force` keyword argument to `schema.drop` to allow for dropping of tables without being prompted. This is a quicker …
=> Support usage of special keywords in table definition

datajoint/user_relations.py, datajoint/utils.py
Fix issues #305 and #306 
* user prompts (e.g. when confirming `delete` or `drop`) now ignores the case of the response and thus can accept answers like `Yes`, `YES`, `No`, and `NO` in an expected fashion.
* calling `help` pydoc functionon `dj.UserRelation` subclasses no longer returns errors
=> Fix hick up with `help()` and better user response handling

datajoint/schema.py
It's a useful thing to know sometimes. Came across that when storing thousands of pytorch models in the DB.
=> `size_on_disk` property for schema

datajoint/autopopulate.py, datajoint/fetch.py
1. Sometimes it is useful to specify the maximal number of keys that should be populated. For instance, when running memory intensive jobs on a cluster so only one of two populations can run at a time, it would be nice to take turns. Setting `limit=1` allows one key to be populated instead of all keys to be exhausted before the other relation can be populated. 
2. Fixed the `to_dicts` function. Before, it returned numpy datatypes in the dictionary which was different from `rel.fetch.keys()` and could not be inserted back into a table. Now, the dictionaries have native python datatypes.
=> introduce limit in populate, fix bug in fetch

.travis.yml, DevDockerfile, Dockerfiles/cuda/Dockerfile, JupyterDockerfile, MANIFEST.in, datajoint/erd.py, docker-compose.yml, misc/db_setup.sql, misc/dev-requirements.txt, requirements.txt, setup.py, test_requirements.txt
Fixed #338 and #340
* If errors are encountered during `matplotlib` or `pygraphviz` import, `dj.ERD` is replaced with a stub function that issues warnings when invoked, fixing #338
* `MANIFEST.in` has been added to include `requirements.txt` into the source distribution, thereby fixing #340
* All `Dockerfile`s except for the main `Dockerfile` has been removed in accordance to the proposal in #339 
* Reflecting #338, `pygraphviz` and `matplotlib` are no longer part of strict requirements as spelled out in `requirements.txt`.
* A separate file `test_requirements.txt` listing packages that should be installed to fully test DataJoint (i.e. `pygraphviz` and `matplotlib`). `.travis.yml` has been updated to reflect this change.
=> Clean up DataJoint project, fix #338 and #340, and reorganize package content

datajoint/base_relation.py, tests/schema.py, tests/test_relation.py
Discussed with @dimitri-yatsenko -
Rather than getting deep into the rest of the query building mechanism, short-circuit this case and build a custom query from the fields in the destination table.
Table alias required by query is of the form ___<rel1>_IFR_<rel2> in order to reduce the likelihood of namespace collisions.
=> fix for 'ignore_extra_fields'/insert select (datajoint-python#355)

datajoint/base_relation.py, datajoint/settings.py, tests/test_relation.py
Recast the mysql InternalError to DataJointError in the specific case of extra columns given in insert-from-select queries.
=> Fix for specific MySQL exception discussed in #35[567].

MANIFEST.in, datajoint/schema.py, tests/test_schema.py
Fix #365. 
As a side note, in the process of testing I've encountered a bug case as reported in #368, which should be dealt with separately.
=> Fix errors with overlapping part table name

CHANGELOG.md, datajoint/base_relation.py, datajoint/declare.py, datajoint/dependencies.py, datajoint/relational_operand.py, datajoint/user_relations.py, tests/schema_advanced.py, tests/test_cascading_delete.py, tests/test_foreign_keys.py, tests/test_relation_u.py
* Fixed #342 
* Fixed #300 -- restructured the delete method and passed regression but have not yet fixed the cascading across renamed foreign keys
* Fixed #370
=> Fixed #342, #370 and restructured the delete method for fixing #300  

datajoint/base_relation.py, datajoint/connection.py, datajoint/jobs.py, datajoint/settings.py, tests/test_relation.py
Fix #382
* `ignore_errors` in `insert` is now deprecated - errors are no longer suppressed with this option and warnings are returned notifying users of this deprecation
* `skip_duplicates=True` no longer suppresses other errors
* Add simple test case to detect side effect due to `skip_duplicates=True`
* Known MySQL errors are re-represented as DataJoint errors with helpful error messages
=> Fix #382 - deprecate `ignore_errors` and fix errorneous `skip_duplicates` behavior

datajoint/erd.py, test_requirements.txt
This uses pydot, which in turn uses an executable for layout rather than native graphviz c-api calls
and so avoids python/graphviz/pygraphviz build complications on Win64.
Should fix #353.
Limited testing appears OK (2 node 'Foo'->'Bar' plot, older version of RET1 schema).
Would probably be good to do more extensive testing to ensure plotting holds -
Of note - multi-schema plots & node renames have not yet been tested.  
Possible TODOs:
- dispatch to native on non-windows platforms instead of entirely switching?
- attempt to locate graphviz install in common places to simplify configuration?
(have not looked into what mechanisms are available to set executable called yet)
=> pydot ERD patch 

datajoint/relational_operand.py
I noticed that the preview for some tables does not always maintain the same column order as in the table definition. This only seems to happen for tables with blob columns. It looks like blobs are being inadvertently pushed to the end of the table preview. This simple PR fixes that. I've only tested `preview()`, not `_repr_html_()`. I'm not sure if the `rel.heading.attributes[c].comment` line in `_repr_html_()` should also be changed to `self.heading.attributes[c].comment`.
=> Maintain column order in preview(), despite blob columns

datajoint/erd.py
handled in erd vs base_relation.lookup_class_name.
fixes #393 
other option would be to modify 'lookup_class_name'; this seems less intrusive
and localized to the problem - other uses of lookup_class_name do not need/use
'module' component and skipping search in '_' there could potentially cause
undefined behavior in some corner cases.
=> erd.py: fix for #393 

datajoint/autopopulate.py, datajoint/declare.py, datajoint/erd.py, datajoint/schema.py, tests/schema_advanced.py
Improved messages, fixed a bug that arose in the handling of the following declaration, for example:
```python
@schema
class InputCell(dj.Manual):
definition = """
-> Cell
(input)-> Cell(cell)
"""
```
This used to throw an error
=> refactor the parsing of foreign keys

datajoint/autopopulate.py, datajoint/base_relation.py, datajoint/dependencies.py, datajoint/erd.py, tests/test_foreign_keys.py
Several years ago, we decided not to query the information schema because it caused some server crashes.  To load dependencies, we parsed the `SHOW CREATE TABLE` statements for each table to extract the foreign keys.  This had many limitations such as the inability to see downstream dependencies for example.  We now believe that those problems have been addressed.  This pull request replaces the loading of dependencies.
=> Load dependencies from information_schema

datajoint/__init__.py, datajoint/base_relation.py, datajoint/dependencies.py, datajoint/external.py, datajoint/relational_operand.py, tests/test_external.py, tests/test_external_class.py, tests/test_foreign_keys.py
Simplify and correct the logic of restrictions.
This PR includes #403 and should be merged after #403 
Also, fix #406:  `"KEY"` can be used in place of `dj.key`.
=> Revamp of restriction

datajoint/external.py
The earlier use of filecopy was a mistake.  Should have always been os.rename
=> eliminate unnecessary copy of external file

CHANGELOG.md, datajoint/base_relation.py, datajoint/external.py, datajoint/schema.py, datajoint/user_relations.py, tests/schema.py, tests/schema_external.py, tests/test_external_class.py, tests/test_s3_mock.py
Implement garbage collection for external. 
In creation of the `schema` decorator, the context keyword now defaults to the local context.
Before:
```python
schema = dj.schema('pipeline_tuning', locals())
```
After
```python
schema = dj.schema('pipeline_tuning')
```
The default context value should also fix #368.
Also fixed #379.
=> Local context; garbage collection

datajoint/external.py
I had some tables in my database, where I wanted to make external attributes nullable. I looked at the code and added two lines.
=> Allow external attributes to be nullable

datajoint/base_relation.py, datajoint/dependencies.py, datajoint/erd.py, requirements.txt
Fixes for networkx version>2
Not heavily tested - unit tests and manual ERD draw for simple single schema set of relations OK.
=> networkx-2 support 

datajoint/jobs.py
Fix for #470.
Only tested against current unit tests on unix, which obviously is not a very good test in terms of completeness or correctness. Will hope to do a proper run on windows and also verify the jobs unit test covers the case (probably does, but not 100%), unless someone else feels more confident about impact.
Also, `os.getpid()` does work on windows; this was verified even if actual change was not otherwise.
=> datajoint/jobs.py: use platform.node() for windows (fix for #470)

datajoint/declare.py, datajoint/query.py, datajoint/schema.py, datajoint/table.py, tests/schema.py, tests/schema_advanced.py
* Fix issue #436, including `describe`
* Backward compatibility is maintained
* Only projections are allowed in dependencies.  Dependencies on more complex expressions should be reissues as separate issues.
=> implement projected dependencies (fix #436)

README.md, datajoint/blob.py, datajoint/connection.py, datajoint/errors.py, datajoint/jobs.py, datajoint/settings.py, tests/test_blob.py, tests/test_connection.py, tests/test_jobs.py, tests/test_reconnection.py
* Fix #279 - Connection to the database is automatically recovered. If the connection was in a transaction, this triggers a `DataJointError`
* Fix #428 and #519 - Packing of `Decimal` and `Datetime` objects into a blob is now supported by converting them into supported datatypes of float and string, respectively.
=> Fix #279, 428, and 519

datajoint/declare.py
`bool`, `boolean`, `real`, and `numeric` are not independent datatypes but are aliases for other data types.   `declare` now accepts them.
=> Fix #544: Accept all aliases for supported datatypes. 

datajoint/table.py
Add clarification about how to override the direct_insert restriction.
... not sure on precise text since the idea of adding this flag was to protect data purity 
& don't want to encourage blind usage, but at the same time, pointers might be useful..
=> datajoint/table.py: add 'see allow_direct_insert' to direct_insert error message

datajoint/declare.py, datajoint/expression.py, datajoint/fetch.py, datajoint/heading.py, datajoint/table.py, datajoint/version.py, tests/schema.py, tests/test_blob2.py, tests/test_foreign_keys.py, tests/test_uuid.py
* Fix #562: It is now possible to declare attributes of type `uuid` which will be translated into `binary16`. The values are inserted and fetched as type `uuid.UUID`.
* Fix #414: `expr.fetch('KEY_ARRAY')` retrieves primary key as record array.
=> fix #562: implement UUID support

datajoint/autopopulate.py, datajoint/declare.py, datajoint/heading.py, datajoint/table.py, datajoint/version.py, tests/schema.py, tests/schema_uuid.py, tests/test_uuid.py
This fixes the bug in the previous release that prevented using UUID attributes in foreign keys.
=> fix foreign keys with UUID-based foreign keys

datajoint/expression.py, datajoint/heading.py, tests/test_relational_operand.py, tests/test_schema_keywords.py
Fix #499  to allow Ellipsis in `proj` and `aggr`
You may now do something like:
```python
q = Person.proj(..., '-date_of_birth')  # all attributes except the date of birth
```
Review after merging #569
=> Fix #499: Proj accepts Ellipsis ... and '-attr' to exclude attributes

datajoint/fetch.py
=> datajoint/fetch.py: teach _get not to call UUID initializer if data is None (fix for #581)

datajoint/expression.py
Fix for #604 - remove attribute check
(provided by @eywalker  / @dimitri-yatsenko )
=> datajoint/expression.py: remove attribute check for #604

datajoint/connection.py
MySQL Server 8.0 completely removed support for the sql_mode = "NO_AUTO_CREATE_USER" thus causing it to fail.
This code creates a connection first without that mode flag and then checks if the server version is greater then 8.0, if not then close the current connection and reconnect with the flag.
This is due to the fact that in 8.0 they enforce the rule of being unable to create accounts via the GRANT command, which is equivalent to this flag always being on.
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_auto_create_user
This might not be the cleanest way to this, so I am be happy to hear feed back.
=> Update Connection.connect() to deal with MYSQL 8.0

CHANGELOG.md, datajoint/dependencies.py, datajoint/diagram.py
Distinguished tables are those that introduce new primary key attributes. They are underlined in the schema diagram. Before this PR, this underlining did not work correctly when the diagram was built by using graph algebra such as `dj.Diagram(table) + 1 - 1`  because the tables were marked as distinguished only in the original diagram. This PR moves the labeling to the point right before plotting, so all tables are checked.
=> Bugfix and optimization of labeling of "distinguished" nodes in diagrams.

setup.py
Use `python_requires` to specify required minimum version. This will make PyPI
aware of the requirement so pip will not try to install it on the wrong version.
I kept the sys.version check in there too as a 'belt-and-suspenders' approach
in case users manage to install it some other way (like with an outdated pip).
=> Update minimum python versioning checks

datajoint/external.py
Before this fix, if an external blob attribute name happened to be a reserved word in MySQL, deleting from the external table would fail with a syntax error. To fix the problem, the attribute name was enclosed in backquotes. 
This issue was discovered in a table that used `signal` as the blob attribute name.
=> Enclose attribute names in backquotes in `ExternalTable.delete`

datajoint/declare.py, datajoint/errors.py, datajoint/external.py, datajoint/heading.py, datajoint/s3.py
enabling compatibility with 0.11
This pull request contains one proposed path for blob migration from version 0.11.* that goes along with the update procedure captured in https://github.com/dimitri-yatsenko/db-programming-with-datajoint/blob/master/notebooks/External-Migration.ipynb
=> blobs can be read from the explicit filepath in the external tables,

datajoint/diagram.py
=> Fix diagram issue when node has no primary keys

datajoint/s3.py, datajoint/settings.py
Add a new optional configuration for S3 protocol storage called `secure` to control  whether S3 connection should be secure or not. Defaults to `False`, and is configured for each storage separately.
Fix #663
=> Add support for secure S3 connection. Fix #663

.gitignore, .travis.yml, CHANGELOG.md, datajoint/external.py, datajoint/fetch.py, datajoint/version.py, docs-parts/admin/5-blob-config_lang1.rst, docs-parts/intro/Releases_lang1.rst, tests/schema_adapted.py, tests/test_adapted_attributes.py, tests/test_filepath.py
- Fix #684
- Minor docs update
- Update Travis to utilize Python3.8
- Update `CHANGELOG.md` and `Releases_lang1.rst`
- Bump version
- Add test case for adapted type with `filepath`
- Fix `filepath` test cases
=> Correct Attribute Adapter from casting to string + minor updates

CHANGELOG.md, datajoint/external.py, datajoint/version.py, docs-parts/intro/Releases_lang1.rst, tests/schema_external.py, tests/test_blob_migrate.py, tests/test_external.py
Fix #692
Currently, on `fetch` the root of the `location` from `s3` storage is stripped but not on `insert`. This change is to align both so that `insert` and `fetch` both strip the root for `s3` storage. This makes it compatible with all S3 providers e.g. Minio does not allow objects on root of `bucket` but AWS hosted objects are allowed. 
`file` storage, however, will still allow `insert` on root.
=> Strip root from external S3 storage on insert

datajoint/errors.py
=> datajoint/errors.py: DataJointError (re-)subclass from Exception (fix for #701)

CHANGELOG.md, datajoint/blob.py, datajoint/heading.py, datajoint/schema.py, datajoint/table.py, datajoint/user_tables.py, datajoint/version.py, docs-parts/intro/Releases_lang1.rst, tests/schema.py, tests/test_blob.py, tests/test_declare.py, tests/test_relation.py
* Fix #698 -- Help now works for DataJoint classes
* Fix #699 -- table definition is appended to doc string
=> Fix #698 and #699

CHANGELOG.md, datajoint/autopopulate.py, datajoint/blob.py, datajoint/connection.py, datajoint/diagram.py, datajoint/heading.py, datajoint/jobs.py, datajoint/schema.py, datajoint/table.py, datajoint/user_tables.py, datajoint/version.py, docs-parts/intro/Releases_lang1.rst, requirements.txt, tests/schema.py, tests/test_alter.py, tests/test_blob.py, tests/test_declare.py, tests/test_jobs.py, tests/test_relation.py
Here's a stab at addressing issue #695. This adds a `multiprocess` kwarg to `populate()`. From what I can tell, building a subset of our database (with about 40 AutoPopulate tables, some with up to 1M rows) with the default single process is as fast as before, around 10-11 min on our 16 core server. With `multiprocess=True` (which in our case spawns a pool of at most 16 processes, depending on the number of primary keys per table), that drops to around 2 min, so about 1/5 the time. The end result looks exactly the same, including table entry order and returned error lists. Besides often having fewer than 16 primary keys per table, I think much of the lost time is due to some individual keys taking much longer to process than others. Since the granularity of the multiprocessing is at the …
=> Add multiprocessing to AutoPopulate

.gitignore, .travis.yml, LNX-docker-compose.yml, README.md, datajoint/declare.py, datajoint/table.py, local-docker-compose.yml
- Update Log table to auto increment entries to prevent collisions and increase timestamp precision to millisecond.
- Add docs that describe how to run tests locally.
=> Update Log table

CHANGELOG.md, LNX-docker-compose.yml, datajoint/blob.py, datajoint/version.py, tests/schema_adapted.py, tests/test_adapted_attributes.py, tests/test_blob.py
=> fix #690 -- blob packing/unpacking of native python bool, int, float, and complex.

datajoint/admin.py
Minimal extension of existing dj.kill() to support #740 -
other more extensive reimplementation might be possible (e.g. making a full 'table' of information_schema.processlist) but would require more development effort.
Unsafe dj.kill() added to facillitate usage by automatic scripts
(e.g. job runners which need to terminate stuck/old jobs forcefully)
Also, add HOST field to display to improve usability in multi-host environments
Changes:
- add 'safemode' argument to dj.kill
Value defaults to Null which implies reading the value from current
dj.config['safemode'] option, falling back to True if this is not present.
- add safemode=False dj.kill operation mode
This will apply the given restriction to the processlist query
and kill all matching processes. Number of killed processes will
be …
=> datajoint/admin.py: add unsafe dj.kill option, expand display to include host

datajoint/fetch.py, tests/test_fetch.py
When setting the fetch_format to 'frame' in the dj.config, using attributes in fetch gives an error.
This was easily fixed by setting format='array', when fetch is called again within "if attrs:"
=> fix when fetch_format='frame'

datajoint/table.py, datajoint/user_tables.py, tests/test_attach.py, tests/test_fetch_same.py, tests/test_reconnection.py, tests/test_update1.py
Implement `Table.update1` that works similarly to `insert1`, updating specified secondary attributes.
=> add method update1 to dj.Table

datajoint/admin.py
adjustment per #779 to address deficiencies in #668 / #775
=> datajoint/admin.py: dj.kill order_by extension 1/N (#779)

tests/test_fetch_same.py, tests/test_jobs.py
Apparently nosetests, sometimes did not pass depending on the order they were invoked. This fixes one case when `enable_native_python_blobs` was required but not set in `test_fetch_same`.
=> Test fixes

LNX-docker-compose.yml, datajoint/connection.py, datajoint/schemas.py, local-docker-compose.yml, tests/test_schema.py
fix for #814 
so far fixed:
tests.test_fetch:TestFetch.test_misspelled_attribute
tests.test_reconnection:TestReconnect.test_reconnect
tests.test_reconnection:TestReconnect.test_reconnect_throws_error_in_transaction
tests.test_relation:TestRelation.test_no_error_suppression
remaining:
tests.test_schema:test_unauthorized_database
(seems to currently raise datajoint.errors.AccessError instead
of expected dj.DataJointError; we don't seem to use more 'advanced'
dj error heirarchy, so not sure what to resolve towards)
while here, remove spurious log message in datajoint/schemas.py
also: should probably make requirements.txt >= 10.x as part of this;
some question r.e. scheduling  therefore as a result
=> fixes for PyMySQL 10.x (fix 814)

datajoint/s3.py, requirements.txt, tests/__init__.py
For now I changed to except all errors to make it work. I need to dig more into how minio does error handling to shrink the error scope to be more specific.
=> Fixing Minio newest package version incompability

datajoint/schemas.py, tests/test_schema.py
I just added what I needed for DJGUI for now, as such it returns the raw names to be parsed by the API on the other side.
I can add additional features as people request them like restricting by lookup tables are returning it in a different format.
=> Added basic list_tables function for schema class

README.md
fix #828
Used static image from shields.io; slack doesn't seem to have native support
for 'badges', and other solutions ( slackin ) are nice in providing a activity
count, but require running a service gateway. In any event, it's a href that works (for now).
=> README.md: flip gitter badge to slack (#828)

datajoint/schemas.py, datajoint/version.py, tests/schema_university.py, tests/test_schema.py, tests/test_university.py, tests/test_update1.py
Fixed an issue when schemas were created with `create_schema=False`
=> Cleanup `schema.activate` logic

.github/workflows/development.yaml, CHANGELOG.md, datajoint/condition.py, datajoint/connection.py, datajoint/diagram.py, datajoint/expression.py, datajoint/schemas.py, datajoint/table.py, datajoint/version.py, docs-parts/intro/Releases_lang1.rst, tests/__init__.py, tests/schema.py, tests/schema_simple.py, tests/test_erd.py, tests/test_relational_operand.py, tests/test_schema.py
=> Fix complex date restriction regression and various others

CHANGELOG.md, datajoint/plugin.py, docs-parts/intro/Releases_lang1.rst, requirements.txt, setup.py
This rename was necessary and allows us to achieve the following:
- Prepares the `otumat` dependency to be `conda-forge` compatible.
- Prepares the `otumat` dependency to be more generic so that other utilities can be introduced (such as usage tracking)
Will follow this with a new release so that we can catch up our conda distro properly. It is currently at `0.12.9` due to several issues.
=> Rename `setuptools_certificate` dependency to `otumat`

CHANGELOG.md, datajoint/autopopulate.py, datajoint/schemas.py, datajoint/version.py, docs-parts/intro/Releases_lang1.rst, tests/test_autopopulate.py, tests/test_erd.py, tests/test_schema_keywords.py
=> Fix dependency load issue on populate

CHANGELOG.md, LNX-docker-compose.yml, datajoint/blob.py, datajoint/table.py, docs-parts/intro/Releases_lang1.rst, local-docker-compose.yml
Fix #938.
Numpy 1.20 deprecated the use of numpy aliases of built-in types. Replacing the aliases with the built-in types does not change behavior but will silence the deprecation warning. 
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
=> Replace use of numpy aliases of built-in types with built-in type

.github/workflows/development.yaml, CHANGELOG.md, LNX-docker-compose.yml, README.md, datajoint/external.py, datajoint/s3.py, docs-parts/intro/Releases_lang1.rst, local-docker-compose.yml, tests/test_s3.py
Fixes bug with minio related to #952, old minio error no longer exists.
Added functionality to external delete to return external delete object errors as error object or string using the new 
flag errors_as_string.
Note that the functionality of external.delete() returning an error table of (uuid, external_path, str(errors)) is maintained.
For the test to work you must use a newer version of the minio docker image in your .env, I have updated the readme to reflect that.
Also updated docker-compose file under the app container to add the minio terminal client for testing.
```shell
wget -P /home/dja/.local/bin/ https://dl.min.io/client/mc/release/linux-amd64/mc
chmod +x /home/dja/.local/bin/mc
mc alias set myminio/ http://minio:9000 datajoint datajoint
```
fixed styling in code to match …
=> Fix return instead of raise, added test to check for s3Error

LNX-docker-compose.yml, README.md, local-docker-compose.yml, tests/__init__.py, tests/test_s3.py
I have found a way to run the test_S3.py test_remove_object exception without using minio client MC.
We should no longer get these errors https://github.com/datajoint/datajoint-python/runs/3571645577?check_suite_focus=true#step:6:2203 
I have also updated the readme to remove instructions to install minio client and updated the docker compose files to remove the minio client install as well.
=> Remove MC dependency.

datajoint/s3.py, datajoint/settings.py
This PR adds the possibility to configure a proxy server for the mini / aws s3 storage. The PR resolves https://github.com/datajoint/datajoint-python/issues/961 .
=> Adds proxy server to minio / aws s3 storage

CHANGELOG.md, datajoint/expression.py, docs-parts/intro/Releases_lang1.rst, requirements.txt, tests/test_aggr_regressions.py
in 0.13.2 we are improperly forming the sql query when we perform a union and then a join, below are the `make_sql()`'s comparing 0.13.2 to 0.12.9:
```python
(q1 + q2).make_sql() #0.13.2
```
```sql
(SELECT DISTINCT `table_a`,`table_b` FROM `test`.`table_b` WHERE(table_a < 3)) 
UNION 
(SELECT DISTINCT `table_a`,`table_b` FROM `test`.`table_b` WHERE(table_a > 3))
```
```python
((q1 + q2) * TableA).make_sql() #0.13.2
```
```sql
SELECT DISTINCT `table_a`,`table_b` 
FROM (
SELECT DISTINCT `table_a`,`table_b` 
FROM `test`.`table_b` 
WHERE(table_a < 3)) as `$8` 
NATURAL JOIN (
SELECT DISTINCT `table_a`,`table_b` FROM `test`.`table_b` 
WHERE(table_a > 3)
) as `$9`
```
```python
(q1 + q2).make_sql() #0.12.9
```
```sql
SELECT `table_a`,`table_b` 
FROM (
SELECT `table_a`,`table_b` 
FROM …
```
=> Fix #930 union join bug, Add test for union join.

datajoint/diagram.py
Changed a comment linking to graphviz's site. Previous link 404'd, updated with the current list of attributes.
[Archived view of old link](https://web.archive.org/web/20121003105920/http://www.graphviz.org/content/attrs) vs. [Updated link](https://graphviz.org/doc/info/attrs.html).
=> Update graphviz attribute list site, old link 404d

datajoint/autopopulate.py, datajoint/table.py
* Fix issue #980
In the default key_source, the secondary attributes must be projected out before joining them.
=> Fix default key_source

CHANGELOG.md, LNX-docker-compose.yml, datajoint/table.py, datajoint/utils.py, docs-parts/intro/Releases_lang1.rst, test_requirements.txt, tests/schema_simple.py, tests/test_cascading_delete.py, tests/test_schema.py
=> fix 151 and 374 - cascades to part tables must be from parent tables.

datajoint/dependencies.py, tests/test_declare.py
- Removed error throw for uniting parts with missing masters
- Added test case for #927
The `unite_master_parts` method raised an error for lists that contained a part table without its master. Removing this fixes #927 without breaking any tests.
=> fix issue #927

CHANGELOG.md, datajoint/expression.py, docs-parts/intro/Releases_lang1.rst, tests/test_relational_operand.py
Added handling for when union gets a union object inside its make_sql(), this allows you to do multiple unions.
Took the test from @guzman-raphael comments on the issue linked.
fix #926
=> Fix bug with unions.

datajoint/__init__.py, datajoint/connection.py, datajoint/table.py, docs-api/docker-compose.yaml, docs-api/source/index.rst, docs-api/source/submodules.rst
- Fix `.rst` parsing issues in docstrings
- add docker command reference to assist iteration while developing
- update structure to show more content in tree on initial navigation
- display API documentation for `datajoint` module by default and set as home.
=> Minor navigation experience improvements to API docs

CHANGELOG.md, LNX-docker-compose.yml, datajoint/__init__.py, datajoint/autopopulate.py, datajoint/connection.py, datajoint/declare.py, datajoint/diagram.py, datajoint/expression.py, datajoint/fetch.py, datajoint/heading.py, datajoint/logging.py, datajoint/plugin.py, datajoint/s3.py, datajoint/schemas.py, datajoint/settings.py, datajoint/table.py, datajoint/version.py, docs-parts/intro/Releases_lang1.rst, local-docker-compose.yml, tests/test_fetch.py
Adds a package level logger for the datajoint package.
~~- [ ] Evaluate log DB table to see if logging needs to be added~~
~~- [ ] log warnings when user calls populate on empty `key_source`~~
~~- [ ] debug level logging for any insert/delete~~
See the converted test `test_limit_warning` in the PR.
Basically you add a handler to the logger that sends all logs to a StringIO object and then retrieve the string from the object, then you remove the handler.
=> Add centralized logger.

.github/workflows/development.yaml
Use heredocs for multiline environment variables between steps.
=> GHA: Add release body validation step

CHANGELOG.md, LNX-docker-compose.yml, README.md, datajoint/table.py, docs/src/query-lang/common-commands.md, local-docker-compose.yml, tests/test_university.py
=> Add support for insert CSV

CHANGELOG.md, LNX-docker-compose.yml, datajoint/version.py, docs/.docker/pip_requirements.txt, docs/src/.overrides/assets/stylesheets/extra.css, local-docker-compose.yml
This PR fixes the readability of the Jupyter Notebook outputs in the `Using the json type` tutorials. This resolves [issue 1078](https://github.com/datajoint/datajoint-python/issues/1078). 
Below are the screenshots from local testing after applying changes to the code as seen in this PR: 
Dark mode - the font in the tables previously appeared white, and was therefore, not readable. See linked issue above for images.
Light mode - there was no issue here previously and remains the same as before.
=> Fix readability of tutorials in dark mode

datajoint/connection.py
To address #1110, I've added this error code to the set of checks performed by `translate_query_error`. 
To protect against potential issues for MySQL 5.7 users, I checked error code manuals for both [5.7](https://dev.mysql.com/doc/mysql-errors/5.7/en/server-error-reference.html) and [8.0](https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html), which indicated that theses error codes would be categorized as `IntegrityError` across both cases.
Are additional tests required for this change?
=> Add MySQL 8 error code for cascade delete 

tests/conftest.py, tests/schema_aggr_regress.py, tests/schema_uuid.py, tests/test_aggr_regressions.py, tests/test_erd.py
- cp to tests
- Migrate schema_uuid
- Fix test tests/test_aggr_regressions.py::test_left_join_len
- Tests pass with module scoped fixtures
- Fix fixtures
- If we skip these, test_union_join passes
- Skipping TestIssue558 passes all
- Tests passing with reordering
- test_aggr_regressions passing
- Construct schema_aggr_reg_with_abx separately
- Add context to diagram tests
=> PLAT-146: Migrate test_aggr_regressions.py

tests/conftest.py, tests/test_external.py
- cp to tests
- nose2pytest test_external
- Use pytest tmpdir fixtures for mocking stores
- Migrate test_external
=> PLAT-154: Migrate test_external

tests/conftest.py, tests/test_external.py, tests/test_external_class.py
- Changes from #1127
- cp to tests
- Migrate test_external_class
=> PLAT-155: Migrate test_external_class

tests/schema.py, tests/test_fetch.py
- Changes in #1127
- Changes in #1128
- cp to tests
- First pass at migrating test_fetch
=> PLAT-156: Migrate test_fetch

tests/conftest.py, tests/schema.py, tests/test_fetch_same.py, tests/test_jobs.py
- Changes from #1129
- Changes from #1130
- cp to tests
- nose2pytest test_jobs
- All but two test_jobs passing
- Clean jobs table in fixture
- Change from generator to list
- Tolerate error when cleaning up schema_any.jobs
=> PLAT-159: Migrate test_jobs

tests/test_reconnection.py
- No changes from previous PRs. This branch was forked directly from `dev-tests`.
- cp to tests
- nose2pytest test_reconnection
- Migrate test_reconnection
=> PLAT-161: Migrate test_reconnection

tests/test_relation.py
- cp to tests
- nose2pytest test_relation
- WIP migrate test_relation
- Move tests to top level
- Fix typo in test
=> PLAT-162: Migrate test_relation

tests/schema.py, tests/test_relational_operand.py
- cp to tests
- nose2pytest test_relational_operand
- First pass at migrating test_relational_operand
=> PLAT-163: Migrate test_relational_operand

tests/conftest.py, tests/test_tls.py
- Checkout conftest from dev-tests-plat-166-schema
- cp to tests
- nose2pytest test_tls
- Migrate test_tls
=> PLAT-167: Migrate test_tls

tests/test_update1.py
- cp to tests
- nose2pytest test_update1
=> PLAT-169: Migrate test_update1

tests/conftest.py, tests/test_schema.py
- cp to tests
- nose2pytest test_schema
- Add db_creds_test fixture
- First pass at migrating test_schema
- Mock schema_empty module
- Move call to spawn_missing_classes to test
=> PLAT-166: Migrate test_schema

docs/src/develop.md
Update the developer docs as scoped in [PLAT-144](https://datajoint.atlassian.net/browse/PLAT-144).
As far as I know, this only includes `docs/src/develop.md`.
=> PLAT-144: Update developer docs

CHANGELOG.md
Add changes from #1142 to the CHANGELOG.
=> PLAT-164: Update CHANGELOG

CHANGELOG.md, datajoint/autopopulate.py, tests_old/test_autopopulate.py
This PR is somewhat related to https://github.com/datajoint/datajoint-python/pull/1062
Currently, the `max_calls` still does not achieve the expected behavior in cases of existing `reserved` jobs.
Consider the case where there already are 2 reserved jobs (two other processes working on one table with `reserve_jobs=True`). Another call of `Table.populate(max_calls=1, reserve_jobs=True)` will exit right away, instead of working the next one job (the expected behavior). 
This is because the list of jobs to be worked on next also include the "reserved" ones, then `max_calls=1` leads to selecting the one that is already "reserved".
This PR fixes the described problem.
However, there is a bit of a redundancy here, the logic to exclude "reserved" jobs already exists in `.populate1()`, just not …
=> exclude "reserved" jobs in `Autopopulate.populate`

.github/workflows/development.yaml, datajoint/autopopulate.py, datajoint/blob.py, datajoint/connection.py, datajoint/declare.py, datajoint/diagram.py, datajoint/expression.py, datajoint/fetch.py, datajoint/heading.py, datajoint/preview.py, datajoint/s3.py, datajoint/settings.py, datajoint/table.py, tests/schema_simple.py, tests/test_utils.py, tests_old/schema_simple.py, tests_old/test_utils.py
Directories `datajoint`, `tests`, and `tests_old` are not compliant with the Black code style as of [`black` v24.2.0](https://black.readthedocs.io/en/stable/change_log.html#id1). This causes [linting errors in CI](https://github.com/datajoint/datajoint-python/actions/runs/7994726865/job/21833444126?pr=1152).
This PR runs the newest version of `black` on our codebase:
```console
$ black datajoint tests tests_old
All done! ✨ 🍰 ✨
132 files left unchanged.
$ black --version
black, 24.2.0 (compiled: yes)
Python (CPython) 3.11.4
```
This PR also includes changes that standardize how `black` is run in CI. These changes were made to address inconsistencies in formatting between different versions of black.
=> Format with black v24.2.0

CHANGELOG.md, datajoint/expression.py, datajoint/table.py, tests/conftest.py, tests/schema.py, tests/test_cascading_delete.py, tests/test_dependencies.py
- Adds line to solve #1159 
- Adds test of edge case demonstrated in above issue
- Tests for cascading delete pass locally
- Pytests show unrelated errors related to an SSL certificate
> WARNING  urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)'))': /datajoint.test
=> Cascade restriction attribute

.github/workflows/development.yaml, CHANGELOG.md
Use of `docker-compose` instead of subcommand `docker compose` breaks CI jobs [such as this one](https://github.com/datajoint/datajoint-python/actions/runs/10222188835/job/28413114065?pr=1163) and blocks #1163.
=> Fix docker compose commands in CI

.github/workflows/development.yaml, .github/workflows/docs.yaml, CHANGELOG.md, requirements.txt, setup.py
To close #1162 
Happy to make other contributions as necessary to upgrade the minimum version.
=> Bumped minimum version to 3.8

CHANGELOG.md, datajoint/expression.py, datajoint/table.py, docs/src/manipulation/delete.md, tests/conftest.py, tests/schema_simple.py, tests/test_cascading_delete.py, tests/test_erd.py, tests/test_schema.py
#151 included a discussion of 'Option 2' in which the master would be deleted during a cascade, with a possible solution proposed in this PR. This feature would be particularly useful to the Spyglass team because our ['Merge tables'](https://lorenfranklab.github.io/spyglass/0.5/misc/merge_tables/) make use of foreign-key references in parts to version pipelines. 
Happy to incorporate feedback
=> Allow including master table in cascading delete

.github/workflows/development.yaml, CHANGELOG.md, datajoint/diagram.py, datajoint/version.py
Encapsulates node names and edge attribute `attr_map` in double quotes before calling `to_pydot` in method `Diagram.make_dot`. Partially duplicates changes made in #1176.
Closes https://github.com/datajoint/datajoint-python/issues/1175 and closes https://github.com/datajoint/datajoint-python/issues/1169 and closes https://github.com/datajoint/datajoint-python/issues/1100 and closes https://github.com/datajoint/datajoint-python/issues/1065. May close related issue https://github.com/datajoint/datajoint-python/issues/1072.
=> Fix Diagram.make_dot for pydot 3.* compatibility

README.md, docs/README.md, docs/src/index.md, docs/src/query/operators.md, docs/src/tutorials/dj-top.ipynb, docs/src/tutorials/json.ipynb, pyproject.toml
This PR updates proposed URLs. **Note**: new links aren't functional yet, please consider before merging.
=> fix(URL): broken routing and redirects on docs.datajoint.com
